site_name: Script for opening and closing a Windows app
site_url: https://josh-wong.github.io/app-open-close-script/
site_description: Automate the process of opening a specific app, allowing data to sync, and then close the app.

# Add repository details in the top right-hand corner
repo_name: josh-wong/app-open-close-script
repo_url: https://github.com/josh-wong/app-open-close-script
# > **Warning**
# >
# > This edit page button does not work. I have prioritized the 
# multidocs site, so the edit page button on https://josh-wong.github.io 
# is correct; there doesn't seem to be a way to remove it from one site 
# and keep it on the other.
edit_uri: blob/main/

plugins:
  - search
  #- techdocs-core
  # Show the last updated date
  - git-revision-date-localized:
      type: date
  # Show docs contributors
  - git-committers:
      repository: josh-wong/app-open-close-script
      branch: main
  # Enable videos to be embedded
  - mkdocs-video:
      css_style:
        width: "100%"
        height: "300px"
  # Add support for RSS
  - rss:
      abstract_chars_count: 160  # -1 for full content
      categories:
        - tags
      comments_path: "#__comments"
      date_from_meta:
        as_creation: "date"
        as_update: false
        datetime_format: "%Y-%m-%d"
      enabled: true
      feed_ttl: 1440
      image: https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/128px-Feed-icon.svg.png
      length: 20
      pretty_print: false
      match_path: ".*"
      url_parameters:
        utm_source: "documentation"
        utm_medium: "RSS"
        utm_campaign: "feed-syndication"
  # Enable support for social cards (pretty link previews)
  - social

markdown_extensions:
  # Add support for abbreviations
  - abbr
  # Add styles for buttons
  - attr_list
  # Add emoji support
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # Add support for Material for MkDocs admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      # Add link next to header that allows the user to get a permalink to the heading (still need to copy the URL in the address bar).
      permalink: true

theme:
  name: material
  # Add logos to docs page
  favicon: assets/images/favicon.png
  logo: assets/images/mkdocs_robot.png
  # Add icon to show repository information and link
  icon:
    repo: fontawesome/brands/github
    # Add icons for Material for MkDocs admonitions
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  # Add light & dark theme
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: grey
      accent: blue
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: grey
      accent: blue
  features:
    # Add custom search functions
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tracking
    - navigation.top

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/josh-wong
      name: josh-wong on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/wongjoshua
      name: Joshua Wong on LinkedIn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/josh_in_japan
      name: josh_in_japan on Twitter

nav:
  - Overview: 'index.md'
  - Getting started: '01_getting-started.md'
  - Configuring the script: '02_configuring-script.md' # Add any additional pages as necessary, but be sure to change the page numbering.
  - Conclusion: '03_conclusion.md'
  - References: '04_references.md'
  - Contributions: '05_contributions.md'
  - '': ''
  - 🔶RSS: 'https://josh-wong.github.io/app-open-close-script/feed_rss_updated.xml'
  - '': ''
  - '': ''
  - 🏠Home: 'https://josh-wong.github.io'